### PR TITLE
Favicons and logos

### PR DESCRIPTION
**Pull request by tigerlily-he**
## This PR
* Adds favicons of varying sizes for every device and platform. Fixes https://github.com/BlockchainAtColumbia/ledgerfest-2019/issues/2
* Adds dark and light version of logo on the navigation bar
image
image

### Also
* Deletes .DS_Store files
* Creates .gitignore to ignore future .DS_Store files

### CODE REVIEW

**Comment by Spandyandy** [comment]
Looking good on mine too, it's kind of hard to see "fest" from "ledgerfest" when the background is white. I guess it's not important

**Comment by tigerlily-he** [comment]
Not sure we can really change the logo now....

**Comment by Spandyandy** [comment]
Yeah it's okay. Do you know how to merge _site/index.html? (It's really long compressed html file)

**Comment by tigerlily-he** [comment]
I think I have to rerun "bundle exec jekyll serve" in order to regenerate the html file.

**Comment by tigerlily-he** [comment]
I did a rebase. Can you check that everything that you did is still there? Also if the favicon doesn't load, do a hard refresh (Ctrl+Shift+R)

**Comment by Spandyandy** [comment]
Yeah! Looking good! I think you can merge it

**Pull request merged**
